### ISSUE TITLE
An image isn't visible

### ISSUE THREAD

**Issue by juliannastepha** [juliannastepha/fastness-fixer#1]
@charlie-quinn
For some reason, my sloth.jpg isn't showing up on the live site. Markbot is saying this.
<img width="846" alt="Screen Shot 2019-11-18 at 2 07 25 PM" src="https://user-images.githubusercontent.com/43150245/69081929-0bf9e300-0a0d-11ea-810f-535c597a1887.png">

**Comment by charlie-quinn** [comment]
You've misspelled `snail.jpg` 😅

**Comment by juliannastepha** [comment]
Oops! It does actually say snail.jpg in my code though. I've triple checked to make sure it's all correctly spelled in the code and the image itself.

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`
